/* {\Tt all.h} for \impcore 29 */
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <setjmp.h>
#include <ctype.h>
/* shared type definitions 32a */
typedef struct Name *Name;
typedef struct Namelist *Namelist;   /* list of Name */
/* shared type definitions 34c */
typedef struct Reader *Reader;
/* shared type definitions 34f */
typedef struct XDefreader *XDefreader;
/* shared type definitions 35b */
typedef enum Prompts { NO_PROMPTS, STD_PROMPTS } Prompts;
/* shared type definitions 35e */
typedef enum Echo { SILENT, ECHOING } Echo;
/* shared type definitions 38a */
/* definition of [[va_list_box]] 39a */
typedef struct va_list_box {
  va_list ap;
} va_list_box;
typedef void Printer(FILE *output, va_list_box*);
/* shared type definitions 683d */
typedef struct Parlist *Parlist; /* list of Par */
/* shared type definitions (generated by a script) */
typedef struct Par *Par;
typedef enum { ATOM, LIST } Paralt; 
/* type definitions for \impcore 31d */
typedef struct UnitTestlist *UnitTestlist; /* list of UnitTest */
/* type definitions for \impcore 31e */
typedef struct Explist *Explist; /* list of Exp */
/* type definitions for \impcore 32d */
typedef int Value;
typedef struct Valuelist *Valuelist;     /* list of Value */
/* type definitions for \impcore 32f */
typedef struct Funlist *Funlist; /* list of Fun */
/* type definitions for \impcore 33e */
typedef struct Valenv *Valenv;
typedef struct Funenv *Funenv;
/* type definitions for \impcore (generated by a script) */
typedef struct Exp *Exp;
typedef enum { LITERAL, VAR, SET, IFX, WHILEX, BEGIN, APPLY } Expalt;

/* type definitions for \impcore (generated by a script) */
typedef struct Userfun Userfun; 
typedef struct Def *Def;
typedef enum { VAL, EXP, DEFINE } Defalt; 
/* type definitions for \impcore (generated by a script) */
typedef struct XDef *XDef;
typedef enum { DEF, USE, TEST } XDefalt; 
typedef struct UnitTest *UnitTest;
typedef enum { CHECK_EXPECT, CHECK_ERROR } UnitTestalt;

/* type definitions for \impcore (generated by a script) */
typedef struct Fun Fun;
typedef enum { USERDEF, PRIMITIVE } Funalt; 
/* shared structure definitions 686e */
struct Reader {
    char *buf;               /* holds the last line read */
    int nbuf;                /* size of buf */
    int line;                /* current line number */
    const char *readername;  /* identifies this reader */

    FILE *fin;               /* filereader */
    const char *s;           /* stringreader */
};
/* shared structure definitions (generated by a script) */
struct Par { Paralt alt; union { Name atom; Parlist list; } u; }; 
/* structure definitions for \impcore (generated by a script) */
struct Exp {
    Expalt alt;
    union {
        Value literal;
        Name var;
        struct { Name name; Exp exp; } set;
        struct { Exp cond; Exp true; Exp false; } ifx;
        struct { Exp cond; Exp exp; } whilex;
        Explist begin;
        struct { Name name; Explist actuals; } apply;
    } u;
};

/* structure definitions for \impcore (generated by a script) */
struct Userfun { Namelist formals; Exp body; }; 
struct Def {
    Defalt alt;
    union {
        struct { Name name; Exp exp; } val;
        Exp exp;
        struct { Name name; Userfun userfun; } define;
    } u;
};

/* structure definitions for \impcore (generated by a script) */
struct XDef {
    XDefalt alt; union { Def def; Name use; UnitTest test; } u;
};

struct UnitTest {
    UnitTestalt alt;
    union {
        struct { Exp check; Exp expect; } check_expect; Exp check_error;
    } u;
};

/* structure definitions for \impcore (generated by a script) */
struct Fun { Funalt alt; union { Userfun userdef; Name primitive; } u; }; 
/* structure definitions for \impcore (generated by a script) */
struct Explist {
	Exp hd;
	Explist tl;
};

struct UnitTestlist {
	UnitTest hd;
	UnitTestlist tl;
};

struct Parlist {
	Par hd;
	Parlist tl;
};

struct Valuelist {
	Value hd;
	Valuelist tl;
};

struct Funlist {
	Fun hd;
	Funlist tl;
};

struct Namelist {
	Name hd;
	Namelist tl;
};

/* shared function prototypes 32b */
Name strtoname(const char *s);
const char *nametostr(Name n);
/* shared function prototypes 32c */
Printer printname;
/* shared function prototypes 34d */
char *readline(Reader r, const char *prompt);
/* shared function prototypes 34e */
Reader stringreader(const char *stringname, const char *s);
Reader filereader  (const char *filename,   FILE *fin);
/* shared function prototypes 34g */
XDef readxdef(XDefreader r);
/* shared function prototypes 35a */
XDefreader xdefreader(Reader r, Prompts prompts);
/* shared function prototypes 37f */
void print (const char *fmt, ...);  /* print to standard output */
void fprint(FILE *output, const char *fmt, ...);  /* print to given file */
/* shared function prototypes 38b */
void installprinter(unsigned char c, Printer *fmt);
/* shared function prototypes 38c */
Printer printpercent, printstring, printdecimal;
/* shared function prototypes 38d */
void vprint(FILE *output, const char *fmt, va_list_box *box);
/* shared function prototypes 39b */
void error(const char *fmt, ...);
extern jmp_buf errorjmp;        /* longjmp here on error */
/* shared function prototypes 39c */
typedef enum ErrorMode { NORMAL, TESTING } ErrorMode;
void set_error_mode(ErrorMode mode);
extern jmp_buf testjmp;
/* shared function prototypes 39d */
void checkargc(Exp e, int expected, int actual);
/* shared function prototypes 39e */
Name duplicatename(Namelist names);
/* shared function prototypes 49d */
void report_test_results(int npassed, int ntests);
/* shared function prototypes 683e */
Printer printpar;
/* shared function prototypes 683f */
Parlist readparlist(Reader r, int doquote, Prompts prompts);
/* shared function prototypes 689f */
extern int checkoverflow(int limit);
/* shared function prototypes (generated by a script) */
Par mkAtom(Name atom);
Par mkList(Parlist list);
struct Par mkAtomStruct(Name atom);
struct Par mkListStruct(Parlist list);
/* function prototypes for \impcore 31f */
Printer printexp, printdef;
/* function prototypes for \impcore 32e */
Printer printvalue;
/* function prototypes for \impcore 33d */
Printer printfun;
/* function prototypes for \impcore 33f */
Valenv mkValenv(Namelist vars, Valuelist vals);
Funenv mkFunenv(Namelist vars, Funlist   defs);
/* function prototypes for \impcore 33g */
Value fetchval(Name name, Valenv env);
Fun   fetchfun(Name name, Funenv env);
/* function prototypes for \impcore 34a */
int isvalbound(Name name, Valenv env);
int isfunbound(Name name, Funenv env);
/* function prototypes for \impcore 34b */
void bindval(Name name, Value val, Valenv env);
void bindfun(Name name, Fun   fun, Funenv env);
/* function prototypes for \impcore 35c */
void  evaldef(Def d, Valenv globals, Funenv functions, Echo echo_level);
Value eval   (Exp e, Valenv globals, Funenv functions, Valenv formals);
/* function prototypes for \impcore 35d */
void readevalprint(XDefreader r, Valenv globals, Funenv functions, Echo
                                                                    echo_level);
/* function prototypes for \impcore 49c */
int tests_passed(UnitTestlist tests, Valenv globals, Funenv functions);
/* function prototypes for \impcore (generated by a script) */
Exp mkLiteral(Value literal);
Exp mkVar(Name var);
Exp mkSet(Name name, Exp exp);
Exp mkIfx(Exp cond, Exp true, Exp false);
Exp mkWhilex(Exp cond, Exp exp);
Exp mkBegin(Explist begin);
Exp mkApply(Name name, Explist actuals);
struct Exp mkLiteralStruct(Value literal);
struct Exp mkVarStruct(Name var);
struct Exp mkSetStruct(Name name, Exp exp);
struct Exp mkIfxStruct(Exp cond, Exp true, Exp false);
struct Exp mkWhilexStruct(Exp cond, Exp exp);
struct Exp mkBeginStruct(Explist begin);
struct Exp mkApplyStruct(Name name, Explist actuals);
/* function prototypes for \impcore (generated by a script) */
Userfun mkUserfun(Namelist formals, Exp body);
Def mkVal(Name name, Exp exp);
Def mkExp(Exp exp);
Def mkDefine(Name name, Userfun userfun);
struct Def mkValStruct(Name name, Exp exp);
struct Def mkExpStruct(Exp exp);
struct Def mkDefineStruct(Name name, Userfun userfun);
/* function prototypes for \impcore (generated by a script) */
XDef mkDef(Def def);
XDef mkUse(Name use);
XDef mkTest(UnitTest test);
struct XDef mkDefStruct(Def def);
struct XDef mkUseStruct(Name use);
struct XDef mkTestStruct(UnitTest test);
UnitTest mkCheckExpect(Exp check, Exp expect);
UnitTest mkCheckError(Exp check_error);
struct UnitTest mkCheckExpectStruct(Exp check, Exp expect);
struct UnitTest mkCheckErrorStruct(Exp check_error);
/* function prototypes for \impcore (generated by a script) */
Fun mkUserdef(Userfun userdef);
Fun mkPrimitive(Name primitive);
/* function prototypes for \impcore (generated by a script) */
int     lengthEL (Explist l);
Exp     nthEL    (Explist l, unsigned n);
Explist mkEL     (Exp hd, Explist tl);
Explist popEL     (Explist l);
Printer printexplist;
/* function prototypes for \impcore (generated by a script) */
int          lengthUL (UnitTestlist l);
UnitTest     nthUL    (UnitTestlist l, unsigned n);
UnitTestlist mkUL     (UnitTest hd, UnitTestlist tl);
UnitTestlist popUL     (UnitTestlist l);
Printer      printunittestlist;
/* function prototypes for \impcore (generated by a script) */
int     lengthPL (Parlist l);
Par     nthPL    (Parlist l, unsigned n);
Parlist mkPL     (Par hd, Parlist tl);
Parlist popPL     (Parlist l);
Printer printparlist;
/* function prototypes for \impcore (generated by a script) */
int       lengthVL (Valuelist l);
Value     nthVL    (Valuelist l, unsigned n);
Valuelist mkVL     (Value hd, Valuelist tl);
Valuelist popVL     (Valuelist l);
Printer   printvaluelist;
/* function prototypes for \impcore (generated by a script) */
int     lengthFL (Funlist l);
Fun     nthFL    (Funlist l, unsigned n);
Funlist mkFL     (Fun hd, Funlist tl);
Funlist popFL     (Funlist l);
Printer printfunlist;
/* function prototypes for \impcore (generated by a script) */
int      lengthNL (Namelist l);
Name     nthNL    (Namelist l, unsigned n);
Namelist mkNL     (Name hd, Namelist tl);
Namelist popNL     (Namelist l);
Printer  printnamelist;
